name: MJG SEC Monitor Automation

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-monitor:
    runs-name: Run SEC Monitor
    runs-on: ubuntu-latest
    
    # This line tells the computer: "Go inside the MJG-SEC-Monitor folder first!"
    defaults:
      run:
        working-directory: ./MJG-SEC-Monitor

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: '.' # Checkout everything

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Tools
        run: pip install requests

      - name: Run SEC Monitor
        run: python monitor_sec.py

      - name: Save Results
        run: |
          git config --global user.name "MJG-Monitor-Bot"
          git config --global user.email "actions@github.com"
          git add sec-monitor/filings_log.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Log" && git push)
